name: update-build-ref

on:
  schedule:
    - cron: 15 14 * * 1-5

jobs:
  updateref:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'
    - name: show files
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: Get-ChildItem /assets
    - name: Pull build ref file from dbatools
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/sqlcollaborative/dbatools/master/bin/dbatools-buildref-index.json -OutFile /assets/dbatools-buildref-index.json
    - name: show files
      working-directory: ${{ github.workspace }}
      shell: pwsh
      run: Get-ChildItem /assets
    - name: Commit build ref file if changed
      uses: matheusalbino/git-commit@v1.0.1
      with:
        user-name: wsmelton
        user-email: wshawnmelton@gmail.com
        message: updating build ref file
        github-token: ${{ secrets.GITHUB_TOKEN }}
