name: update-build-ref

on: ['updateref']

jobs:
  updateref:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'
    - name: 'Deployment pending'
      uses: 'deliverybot/status@master'
      with:
        state: 'pending'
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: create remote to dbatools
      shell: pwsh
      run: git remote add dbatools git@github.com:sqlcollaborative/dbatools.git
    - name: fetch dbatools
      shell: pwsh
      run: git fetch dbatools master
    - name: checkout buildref file
      shell: pwsh
      run: git checkout dbatools/master -- bin/dbatools-buildref-index.json
    - name: Move buildref and cleanup
      shell: pwsh
      run: |
        Move-Item bin/dbatools-buildref-index.json assets/dbatools-buildref-index.json -Force -Confirm:$false,
        Remove-Item bin/ -Force -Confirm:$false,
        git reset
    - name: Commit changed file
      shell: pwsh
      run: if ( (git status --porcelain) -ne $null ){ git add .\assets\dbatools-buildref-index.json; git commit -m 'updating buildref file' }
