name: update-build-ref

on:
  deployment

jobs:
  updateref:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'
    - name: 'Deployment pending'
      uses: 'deliverybot/status@master'
      with:
        state: 'pending'
        token: '${{ secrets.GITHUB_TOKEN }}'
    - name: create remote to dbatools
      shell: pwsh
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/sqlcollaborative/dbatools/master/bin/dbatools-buildref-index.json -OutFile assets/dbatools-buildref-index.json
    - name: Commit changes
      uses: EndBug/add-and-commit@v2.1.0
      with:
        author_name: Shawn Melton
        author_email: wshawnmelton@gmail.com
        message: "Update buildref file"
        path: "assets/dbatools-buildref-index.json"
        pattern: "dbatools-buildref-index.json"
        force: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
