name: update-build-ref

on:
  schedule:
    - cron: 58 22 * * *

jobs:
  updateref:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'
    - name: show content of build file
      working-directory: assets
      run: head -2 dbatools-buildref-index.json
    - name: Pull build ref file from dbatools
      run: cd /assets && curl -O https://raw.githubusercontent.com/sqlcollaborative/dbatools/master/bin/dbatools-buildref-index.json
    - name: show content of build file
      working-directory: assets
      run: head -2 dbatools-buildref-index.json
    # - name: Commit build ref file if changed
    #   uses: matheusalbino/git-commit@v1.0.1
    #   with:
    #     user-name: wsmelton
    #     user-email: wshawnmelton@gmail.com
    #     message: updating build ref file
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
