name: update-build-ref

on:
  schedule:
    - cron: 30 13 * * 1-5

jobs:
  updateref:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'
    - name: Pull build ref file from dbatools
      shell: pwsh
      run: Invoke-WebRequest -Uri https://raw.githubusercontent.com/sqlcollaborative/dbatools/master/bin/dbatools-buildref-index.json -OutFile assets/dbatools-buildref-index.json
    - name: Commit build ref file if changed
      uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: uupdating build ref file
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
